baseURL = 'https://ynky120.github.io/'
languageCode = 'zh'
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
title = '雷子的博客'
theme = 'PaperMod'
hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = 8

[[menu.main]]
identifier = "home"
name = "主页"
url = "/"
weight = 1

[[menu.main]]
name = "搜索"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 15

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "时间轴"
url = "/archives/"
weight = 30

[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, links, about..."

[[params.socialIcons]]
name = "<platform>"
url = "<link>"

[[params.socialIcons]]
name = "<platform 2>"
url = "<link2>"

[params]
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowWordCounts = true
VisitCount = true
DateFormat = "2006-01-02"
defaultTheme = "auto"
languageAltTitle = "简体中文"
